apiVersion: v1
kind: ConfigMap
metadata:
  name: settlement-config
data:
  db_host: "postgres-service"
  db_name: "settlement_db"
  app_port: "8081"
  pricing_service_url: "http://pricing-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: settlement-secret
type: Opaque
data:
  db_password: c2V0dGxlbWVudHBhc3M=
  db_user: c2V0dGxlbWVudHVzZXI=