pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "imamaziz/auth-service:v1"
    }
    stages {
        stage('Install Dependencies') {
            steps {
                sh 'go mod tidy'
            }
        }
        stage('Run Functional Tests') {
            steps {
                sh 'go test ./internal/tests/functional/...'
            }
        }
        stage('Build & Push Docker') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE} ."
                sh "docker push ${DOCKER_IMAGE}"
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f deployments/kubernetes/'
            }
        }
    }
}